# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "centos-6.3-chef-roger"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "https://s3.amazonaws.com/itmat-public/centos-6.3-chef-10.14.2.box"

  config.vm.network :public_network, bridge: 'en0: Wi-Fi (AirPort)'

  config.vm.synced_folder "../app", "/roger"
  
  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network :forwarded_port, guest: 80, host: 8888
  config.vm.network :forwarded_port, guest: 5000, host: 5500
  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 2
  end
   config.vm.provision :chef_solo do |chef|
      chef.cookbooks_path = "chef/cookbooks"
      #chef.add_recipe "nodejs::install_from_source_centos"
      chef.add_recipe "roger"
    end
 
end
