appname := roger

CXX := g++
inclDirs := ./src/brain
CXXFLAGS := -g -Wall -I$(inclDirs)
srcfiles := $(shell find ./src -name "*.cpp")
objects  := $(patsubst ./src/%.cpp, ./bin/%.o, $(srcfiles))


all: $(appname)
	@echo $(objects)

$(appname): $(objects)
	@echo $(objects)
	$(CXX) $(CXXFLAGS) -o ./bin/$(appname) $(objects)

depend: .depend

.depend: $(srcfiles)
	rm -f ./.depend
	$(CXX) $(CXXFLAGS) -MM $^>>./.depend;

clean:
	rm -rf ./bin/

dist-clean: clean
	rm -f *~ .depend

include .depend